### ISSUE TITLE
Unable to install in Kali Linux 2021

### ISSUE THREAD

**Issue by rmjaadugar** [sahildari/R3CON#1]
Hello Sahil

Donno where I am going wrong, I am getting this error while cloning. 
![image](https://user-images.githubusercontent.com/95405455/147813459-220f696b-b49e-4c50-ac2b-c04c7812b5a4.png)

**Comment by sahildari** [comment]
Hey @rmjaadugar,
Please try to check the version for git installed on your computer. You can check the git version via `git --version`
Try and update the Kali via `sudo apt update -y && sudo apt upgrade -y`
